version: '3.4'

services:
  eshopdb:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EShopDevDb
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/data

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment: 
      - ACCEPT_EULA=Y
      # - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
      # - SEQ_FIRSTRUN_ADMINEMAIL=admin@example.com    optional, helpful for notifications
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true         # opsi (tidak disarankan) untuk non-auth
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"
    volumes:
      - ./seq-data:/var/lib/seq

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: messagebus
    hostname: ecommerce-mq
    ports:
      - "5672:5672" # port untuk AMQP (digunakan oleh aplikasi)
      - "15672:15672" # port untuk RabbitMQ Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  identity:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: identity
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://eshopdb/EShopDb?currentSchema=identity
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HOSTNAME=http://identity:9090/
      - KC_HTTP_PORT=9090
    restart: always
    ports:
      - "9090:9090"
    command:
      - start-dev

volumes:
  postgres_eshopdb:
