version: '3.4'

services:
  eshopdb:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EShopDevDb
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/data

volumes:
  postgres_eshopdb:
